/**
 * 用途：存放 actionTypes 变量
 * 好处：大型项目的时候避免命名重复，被其他人的冲刷掉 
 */

export const ActionTypes = {
    SET_BASICINFO: 'SET_BASICINFO',
    SET_EXPERIENCE: 'SET_EXPERIENCE',
    SET_SKILL: 'SET_SKILL',
    SET_APPRAISAL: 'SET_APPRAISAL',
    CLEAR_SET_BASICINFO: 'CLEAR_SET_BASICINFO',
    CLEAR_SET_EXPERIENCE: 'CLEAR_SET_EXPERIENCE',
    CLEAR_SET_SKILL: 'CLEAR_SET_SKILL',
    CLEAR_SET_APPRAISAL: 'CLEAR_SET_APPRAISAL',
    NEW_SET_EXPERIENCE: 'NEW_SET_EXPERIENCE',
    NEW_SET_SKILL: 'NEW_SET_SKILL',
    NEW_SET_APPRAISAL: 'NEW_SET_APPRAISAL',
}
